# Generated by Django 3.0.3 on 2020-04-12 19:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=40, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254)),
                ('messagge', models.TextField()),
            ],
            options={
                'verbose_name': 'Conctacto',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField()),
                ('about_title', models.CharField(max_length=50, verbose_name='Titulo Nosotros')),
                ('about_text', models.TextField()),
                ('conctact_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email contacto')),
            ],
            options={
                'verbose_name': 'Pagina Principal',
                'verbose_name_plural': 'Pagina Principal',
            },
        ),
        migrations.CreateModel(
            name='Suscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Subscriptor',
                'verbose_name_plural': 'Subscriptores',
            },
        ),
    ]
