# Generated by Django 3.0.3 on 2020-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='2', max_length=30, verbose_name='Telefono Contacto'),
            preserve_default=False,
        ),
    ]
