# Generated by Django 3.0.3 on 2020-04-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(default='2', max_length=30, verbose_name='Telefono Contacto'),
            preserve_default=False,
        ),
    ]
